const state={members:[
 {id:1,name:'AJAY',completed:0,newTickets:0,development:0,support:0,pending:4,avatar:'#7a3ed1'},
 {id:2,name:'CHANDER',completed:3,newTickets:6,development:0,support:0,pending:8,avatar:'#2477df'},
 {id:3,name:'PAVAN',completed:6,newTickets:11,development:0,support:0,pending:8,avatar:'#1ca36f'},
 {id:4,name:'VENKAT',completed:2,newTickets:1,development:0,support:0,pending:3,avatar:'#ff711d'}
],yesterdayPending:8};
const $=id=>document.getElementById(id);const total=m=>m.newTickets+m.pending;const sum=k=>state.members.reduce((n,m)=>n+(m[k]||0),0);
function totals(){return{total:sum('newTickets')+sum('pending'),completed:sum('completed'),newTickets:sum('newTickets'),development:sum('development'),support:sum('support'),pending:sum('pending')}}
function icon(name){return `<i data-lucide="${name}"></i>`}
function render(){const t=totals();$('lastUpdated').textContent=new Date().toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
 const cards=[['Total Tickets',t.total,'ticket','blue'],['Completed',t.completed,'check','green'],['New Tickets',t.newTickets,'plus','blue'],['Development',t.development,'code-2','purple'],['Dev Support',t.support,'users','teal'],['Pending',t.pending,'clock','orange']];
 $('metrics').innerHTML=cards.map(c=>`<div class="metric ${c[3]}"><div class="circle">${icon(c[2])}</div><div><h3>${c[0]}</h3><strong>${c[1]}</strong>${c[0]==='Pending'?`<small>Yesterday: ${state.yesterdayPending}</small>`:''}</div></div>`).join('');
 let rows=[...state.members];const q=$('searchInput').value.toLowerCase();const cat=$('categoryFilter').value;const sort=$('sortSelect').value;
 rows=rows.filter(m=>m.name.toLowerCase().includes(q));if(cat!=='all')rows=rows.filter(m=>cat==='new'?m.newTickets>0:cat==='support'?m.support>0:m[cat]>0);rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='total'?total(b)-total(a):b.pending-a.pending);
 $('teamTable').innerHTML=rows.map(m=>`<tr><td><div class="person"><span class="avatar" style="background:${m.avatar}">${m.name[0]}</span>${m.name}</div></td><td>${total(m)}</td><td>${m.completed}</td><td>${m.newTickets}</td><td>${m.development}</td><td>${m.support}</td><td>${m.pending}</td><td><button class="action-btn edit" onclick="editMember(${m.id})">${icon('pencil')}</button><button class="action-btn delete" onclick="deleteMember(${m.id})">${icon('trash-2')}</button></td></tr>`).join('');
 $('teamSummary').innerHTML=[['Total Team',`${state.members.length} Members`],['Total Tickets',t.total],['Completed',t.completed],['New Tickets',t.newTickets],['Development',t.development],['Dev Support',t.support],['Pending',t.pending]].map((x,i)=>`<div class="summary-item"><h4>${x[0]}</h4><strong>${x[1]}</strong></div>`).join('');lucide.createIcons();}
function openModal(title,fields,submit){$('modalTitle').textContent=title;$('formFields').innerHTML=fields.map(f=>`<div class="field"><label>${f.label}</label><input name="${f.name}" type="${f.type||'number'}" value="${f.value??''}" ${f.required?'required':''}></div>`).join('');$('modal').classList.remove('hidden');$('modalForm').onsubmit=e=>{e.preventDefault();submit(Object.fromEntries(new FormData(e.target)));closeModal()};}
function closeModal(){$('modal').classList.add('hidden')}$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
window.editMember=id=>{const m=state.members.find(x=>x.id===id);openModal(`Edit ${m.name}`,[{label:'Name',name:'name',type:'text',value:m.name,required:true},{label:'Completed',name:'completed',value:m.completed},{label:'New Tickets',name:'newTickets',value:m.newTickets},{label:'Development',name:'development',value:m.development},{label:'Dev Support',name:'support',value:m.support},{label:'Pending',name:'pending',value:m.pending}],v=>{Object.assign(m,{name:v.name,completed:+v.completed,newTickets:+v.newTickets,development:+v.development,support:+v.support,pending:+v.pending});render()})};
window.deleteMember=id=>{if(confirm('Delete this team member?')){state.members=state.members.filter(m=>m.id!==id);render()}};
$('addMemberBtn').onclick=()=>openModal('Add Team Member',[{label:'Name',name:'name',type:'text',required:true}],v=>{state.members.push({id:Date.now(),name:v.name.toUpperCase(),completed:0,newTickets:0,development:0,support:0,pending:0,avatar:'#3f77c8'});render()});
$('addTicketBtn').onclick=()=>openModal('Add Ticket',[{label:'Team Member ID',name:'id',value:state.members[0]?.id||'',required:true},{label:'Ticket Status (new/pending/completed/development/support)',name:'status',type:'text',required:true}],v=>{const m=state.members.find(x=>x.id===+v.id);if(!m)return alert('Member ID not found');const map={new:'newTickets',pending:'pending',completed:'completed',development:'development',support:'support'};if(map[v.status])m[map[v.status]]++;render()});
$('searchInput').oninput=render;$('categoryFilter').onchange=render;$('sortSelect').onchange=render;
$('exportBtn').onclick=()=>{const csv=['Name,Total Tickets,Completed,New Tickets,Development,Dev Support,Pending',...state.members.map(m=>[m.name,total(m),m.completed,m.newTickets,m.development,m.support,m.pending].join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ticketing-dashboard.csv';a.click();URL.revokeObjectURL(a.href)};
$('snapshotBtn').onclick=()=>window.print();render();
